### ISSUE TITLE
Directly rendering the IDF

### ISSUE THREAD

**Issue by coledea** [yifita/idf#2]
Thanks for your work!
Maybe I overlooked it, but I didn't find any code for rendering the IDF (e.g. by means of sphere tracing). Are you planning to provide such code for rendering the IDF directly, because the images in your paper (where you compare to other work) seem to display such direct renderings.

**Comment by yifita** [comment]
Hi @coledea , the images from the paper are actually rendered using pyrender after marching cube. 
We don't plan to add such code in the short term.
